
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.models3d': '3D Models',
    'nav.contact': 'Contact',
    'nav.cv': 'CV',
    'nav.download_cv': 'Download CV',
    'hero.creative_specialist': 'Creative Specialist',
    'hero.title': 'JULEN VALLECILLOS',
    'hero.subtitle': '3D Artist • Unity Developer • Game Development Trainer',
    'hero.view_projects': 'View Projects',
    'hero.download_cv': 'Download CV',
    'project.actual': 'Current Project',
    'project.in_development': 'In Development',
    'project.neon_run_desc': 'A rhythmic platformer set in a procedural neon world. Using Unity 2022 LTS and advanced VFX systems for a unique visual experience.',
    'project.phase': 'Production Phase: Core Mechanics & Shaders',
    'project.neon_run_name': '"Project NEON-RUN"',
    'andaluzia.title': 'AndaluzIA',
    'andaluzia.subtitle': 'Digital Marketing & AI',
    'andaluzia.desc': 'At AndaluzIA, we merge traditional creativity with the infinite possibilities of AI. I develop high-impact visual marketing experiences using 3D pipelines and generative workflows.',
    'andaluzia.view_agency': 'View Agency',
    'eag.title': 'Granada Art School',
    'eag.subtitle': 'Education',
    'eag.course': 'Introduction to Unity for 2D and 3D Games',
    'eag.desc': 'As a teacher, I guide my students through a 60-hour program. We divide the process into three critical phases to ensure a smooth and professional development.',
    'eag.download_plan': 'Download Plan (PDF)',
    'eag.feature1': 'Custom Mechanics',
    'eag.feature2': 'Particle Systems',
    'eag.feature3': 'C# Logic',
    'eag.feature4': 'Game AI',
    'social.title': 'Julengine',
    'social.desc': 'Explore my tutorials, workflows, and daily content on social media.',
    'social.youtube_desc': 'Devlogs, technical tutorials, and professional workflows.',
    'social.tiktok_desc': 'Quick 3D tips, Unity tricks, and daily insights.',
    'social.instagram_desc': 'My artistic side: Finished renders and visual gallery.',
    'skills.hard': 'Hard Skills',
    'skills.hard_desc': 'I master industry-standard software to bring any vision to the digital field.',
    'skills.soft': 'Soft Skills',
    'skills.soft_desc': 'Interpersonal qualities that enhance workflow and professional collaboration.',
    'experience.title': 'Experience',
    'experience.desc': 'My professional journey building worlds and training future talents.',
    'languages.title': 'Languages',
    'projects.title': 'Projects',
    'projects.subtitle': 'A deep look at my created worlds.',
    'projects.explore_all': 'Explore All',
    'projects.environment': 'Environment',
    'projects.view_details': 'View Details',
    'contact.cta_title': 'SHALL WE TALK?',
    'contact.cta_desc': 'I am available for creative projects, talks, or personalized tutoring. Let\'s build the interactive future together.',
    'contact.cta_button': 'Start',
    'contact.title': 'Let\'s Talk',
    'contact.subtitle': 'Do you have a project in mind or just want to say hi?',
    'contact.label_name': 'Name',
    'contact.placeholder_name': 'Your full name',
    'contact.label_email': 'Email',
    'contact.placeholder_email': 'email@example.com',
    'contact.label_message': 'Message',
    'contact.placeholder_message': 'Tell me about your project...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Message sent successfully! (Simulated)',
    'contact.collabs': 'Collaborators & Friends',
    'contact.your_name': 'Your name',
    'contact.collab_cta': 'Collaborate',
    'projects_page.title': 'My Projects',
    'projects_page.view_more': 'View more',
    'projects.p1_title': 'Cyberpunk Alleyway',
    'projects.p1_desc': 'Immersive environment created in Unreal Engine 5 using Lumen and Nanite.',
    'projects.p2_title': 'Mecha Drone V.2',
    'projects.p2_desc': 'Hard Surface model textured entirely in Substance Painter.',
    'projects.p3_title': 'Abstract Geometry',
    'projects.p3_desc': 'Series of abstract renders exploring caustics and complex materials.',
    'projects.p4_title': 'Ancient Temple',
    'projects.p4_desc': 'Historical reconstruction for an augmented reality project.',
    'projects.p5_title': 'Sci-Fi UI Kit',
    'projects.p5_desc': 'Futuristic interface package designed for Unity 3D.',
    'projects.p6_title': 'Character Rigging',
    'projects.p6_desc': 'Advanced rigging system for bipedal characters in Blender.',
    'models_page.title': '3D Viewer',
    'models_page.subtitle': 'Interact directly with my models. You can rotate, zoom, and inspect the meshes.',
    'models_page.model_label': 'Model',
    'models_page.pbr_desc': 'Produced using Blender for modeling and Substance Painter for PBR (Physical Based Rendering) texturing.',
    'models_page.textures': '4K Textures',
    'models_page.game_ready': 'Game Ready',
    'models.m1_title': 'Modular Space Station',
    'models.m1_desc': 'Modular kitbash designed for optimization in real-time engines.',
    'models.m2_title': 'Underwater Creature',
    'models.m2_desc': 'Organic sculpture with manual retopology workflow.',
    'models.m3_title': 'Post-Apocalyptic Vehicle',
    'models.m3_desc': 'Focus on material wear and micro-details in textures.',
    'footer.rights': 'ALL RIGHTS RESERVED.',
    'skills.blender_desc': '3D modeling, sculpting, and photorealistic rendering for high-quality assets.',
    'skills.photoshop_desc': 'Digital retouching, texture design, and advanced visual post-production.',
    'skills.substance_desc': 'Professional PBR texturing following AAA industry standards.',
    'skills.unreal_desc': 'Creation of immersive worlds, dynamic lighting, and game logic.',
    'skills.unity_desc': 'Integral development of 2D and 3D games, from prototyping to publishing.',
    'skills.premiere_desc': 'Cinematic video editing, montage, and audiovisual narrative.',
    'skills.reaper_desc': 'Sound design and audio production optimized for interactive experiences.',
    'soft_skills.comm': 'Communication',
    'soft_skills.comm_desc': 'Ability to convey technical ideas clearly to non-technical profiles.',
    'soft_skills.team': 'Teamwork',
    'soft_skills.team_desc': 'Experience collaborating in multidisciplinary and remote environments.',
    'soft_skills.problem': 'Problem Solving',
    'soft_skills.problem_desc': 'Analytical approach to overcome technical and creative challenges.',
    'soft_skills.adapt': 'Adaptability',
    'soft_skills.adapt_desc': 'Quick learning of new tools and work methodologies.',
    'soft_skills.lead': 'Leadership',
    'soft_skills.lead_desc': 'Ability to guide teams and projects towards common goals.',
    'soft_skills.time': 'Time Management',
    'soft_skills.time_desc': 'Efficient organization to meet critical milestones and deliveries.',
    'exp.docente_role': 'Game Development Teacher',
    'exp.docente_company': 'Granada Art School',
    'exp.docente_period': '2023 - Present',
    'exp.docente_desc': 'Teaching Unity, C#, and 3D art pipelines for vocational training cycles.',
    'exp.creative_role': 'Creative Specialist',
    'exp.creative_company': 'AndaluzIA',
    'exp.creative_period': '2022 - Present',
    'exp.creative_desc': 'Development of AI-driven visual content and 3D pipelines for digital marketing.',
    'exp.freelance_role': 'Freelance 3D Artist',
    'exp.freelance_company': 'Various Clients',
    'exp.freelance_period': '2020 - 2022',
    'exp.freelance_desc': 'Creation of assets, environments, and architectural visualizations for various projects.',
    'lang.spanish': 'Spanish',
    'lang.english': 'English',
    'lang.basque': 'Basque',
    'lang.native': 'Native',
    'lang.pro': 'Professional (C1)',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.projects': 'Proyectos',
    'nav.models3d': 'Modelos 3D',
    'nav.contact': 'Contacto',
    'nav.cv': 'CV',
    'nav.download_cv': 'Descargar CV',
    'hero.creative_specialist': 'Creative Specialist',
    'hero.title': 'JULEN VALLECILLOS',
    'hero.subtitle': 'Artista 3D • Desarrollador Unity • Formador en Videojuegos',
    'hero.view_projects': 'Ver Proyectos',
    'hero.download_cv': 'Descargar CV',
    'project.actual': 'Proyecto Actual',
    'project.in_development': 'En Desarrollo',
    'project.neon_run_desc': 'Un juego de plataformas rítmico ambientado en un mundo procedural de luces de neón. Utilizando Unity 2022 LTS y sistemas de VFX avanzados para una experiencia visual única.',
    'project.phase': 'Fase de Producción: Core Mechanics & Shaders',
    'project.neon_run_name': '"Project NEON-RUN"',
    'andaluzia.title': 'AndaluzIA',
    'andaluzia.subtitle': 'Marketing Digital & IA',
    'andaluzia.desc': 'En AndaluzIA, fusionamos la creatividad tradicional con las posibilidades infinitas de la IA. Desarrollo experiencias de marketing visual de alto impacto utilizando pipelines 3D y flujos de trabajo generativos.',
    'andaluzia.view_agency': 'Ver Agencia',
    'eag.title': 'Escuela de Arte de Granada',
    'eag.subtitle': 'Educación',
    'eag.course': 'Introducción a Unity para Videojuegos 2D y 3D',
    'eag.desc': 'Como docente, guío a mis alumnos a través de un programa de 60 horas. Dividimos el proceso en tres fases críticas para garantizar un desarrollo fluido y profesional.',
    'eag.download_plan': 'Descargar Plan (PDF)',
    'eag.feature1': 'Mecánicas Propias',
    'eag.feature2': 'Sistemas de Partículas',
    'eag.feature3': 'Lógica en C#',
    'eag.feature4': 'IA en Juegos',
    'social.title': 'Julengine',
    'social.desc': 'Explora mis tutoriales, procesos de trabajo y contenido diario en redes sociales.',
    'social.youtube_desc': 'Devlogs, tutoriales técnicos y pipelines de trabajo profesional.',
    'social.tiktok_desc': 'Tips rápidos de 3D, trucos de Unity y pinceladas del día a día.',
    'social.instagram_desc': 'Mi cara más artística: Renders terminados y galería visual.',
    'skills.hard': 'Hard Skills',
    'skills.hard_desc': 'Domino el software estándar de la industria para llevar cualquier visión al terreno digital.',
    'skills.soft': 'Soft Skills',
    'skills.soft_desc': 'Cualidades interpersonales que potencian el flujo de trabajo y la colaboración profesional.',
    'experience.title': 'Experiencia',
    'experience.desc': 'Mi trayectoria profesional construyendo mundos y formando a futuros talentos.',
    'languages.title': 'Idiomas',
    'projects.title': 'Proyectos',
    'projects.subtitle': 'Una mirada profunda a mis mundos creados.',
    'projects.explore_all': 'Explorar Todo',
    'projects.environment': 'Entorno',
    'projects.view_details': 'Ver Detalles',
    'contact.cta_title': '¿HABLAMOS?',
    'contact.cta_desc': 'Estoy disponible para proyectos creativos, charlas o tutorías personalizadas. Construyamos el futuro interactivo juntos.',
    'contact.cta_button': 'Comenzar',
    'contact.title': 'Hablemos',
    'contact.subtitle': '¿Tienes un proyecto en mente o solo quieres saludar?',
    'contact.label_name': 'Nombre',
    'contact.placeholder_name': 'Tu nombre completo',
    'contact.label_email': 'Email',
    'contact.placeholder_email': 'correo@ejemplo.com',
    'contact.label_message': 'Mensaje',
    'contact.placeholder_message': 'Cuéntame sobre tu proyecto...',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.success': '¡Mensaje enviado con éxito! (Simulado)',
    'contact.collabs': 'Colaboradores & Amigos',
    'contact.your_name': 'Tu nombre',
    'contact.collab_cta': 'Colabora',
    'projects_page.title': 'Mis Proyectos',
    'projects_page.view_more': 'Ver más',
    'projects.p1_title': 'Cyberpunk Alleyway',
    'projects.p1_desc': 'Entorno inmersivo creado en Unreal Engine 5 usando Lumen y Nanite.',
    'projects.p2_title': 'Mecha Drone V.2',
    'projects.p2_desc': 'Modelo Hard Surface texturizado íntegramente en Substance Painter.',
    'projects.p3_title': 'Abstract Geometry',
    'projects.p3_desc': 'Serie de renders abstractos explorando cáusticas y materiales complejos.',
    'projects.p4_title': 'Ancient Temple',
    'projects.p4_desc': 'Reconstrucción histórica para un proyecto de realidad aumentada.',
    'projects.p5_title': 'Sci-Fi UI Kit',
    'projects.p5_desc': 'Paquete de interfaz futurista diseñada para Unity 3D.',
    'projects.p6_title': 'Character Rigging',
    'projects.p6_desc': 'Sistema de rigging avanzado para personajes bípedos en Blender.',
    'models_page.title': 'Visualizador 3D',
    'models_page.subtitle': 'Interactúa directamente con mis modelos. Puedes rotar, hacer zoom e inspeccionar las mallas.',
    'models_page.model_label': 'Modelo',
    'models_page.pbr_desc': 'Producido utilizando Blender para el modelado y Substance Painter para el texturizado PBR (Physical Based Rendering).',
    'models_page.textures': '4K Texturas',
    'models_page.game_ready': 'Game Ready',
    'models.m1_title': 'Estación Espacial Modular',
    'models.m1_desc': 'Kitbash modular diseñado para optimización en motores de tiempo real.',
    'models.m2_title': 'Criatura Submarina',
    'models.m2_desc': 'Escultura orgánica con flujo de trabajo de retopología manual.',
    'models.m3_title': 'Vehículo Post-Apocalíptico',
    'models.m3_desc': 'Enfoque en desgaste de materiales y micro-detalles en las texturas.',
    'footer.rights': 'TODOS LOS DERECHOS RESERVADOS.',
    'skills.blender_desc': 'Modelado 3D, escultura y renderizado fotorrealista para assets de alta calidad.',
    'skills.photoshop_desc': 'Retoque digital, diseño de texturas y post-producción visual avanzada.',
    'skills.substance_desc': 'Texturizado PBR profesional siguiendo estándares de la industria AAA.',
    'skills.unreal_desc': 'Creación de mundos inmersivos, iluminación dinámica y lógica de juego.',
    'skills.unity_desc': 'Desarrollo integral de videojuegos 2D y 3D, desde prototipado hasta publicación.',
    'skills.premiere_desc': 'Edición de video cinematográfica, montaje y narrativa audiovisual.',
    'skills.reaper_desc': 'Diseño sonoro y producción de audio optimizado para experiencias interactivas.',
    'soft_skills.comm': 'Comunicación',
    'soft_skills.comm_desc': 'Capacidad para transmitir ideas técnicas de forma clara a perfiles no técnicos.',
    'soft_skills.team': 'Trabajo en Equipo',
    'soft_skills.team_desc': 'Experiencia colaborando en entornos multidisciplinares y remotos.',
    'soft_skills.problem': 'Resolución de Problemas',
    'soft_skills.problem_desc': 'Enfoque analítico para superar desafíos técnicos y creativos.',
    'soft_skills.adapt': 'Adaptabilidad',
    'soft_skills.adapt_desc': 'Aprendizaje rápido de nuevas herramientas y metodologías de trabajo.',
    'soft_skills.lead': 'Liderazgo',
    'soft_skills.lead_desc': 'Capacidad para guiar equipos y proyectos hacia objetivos comunes.',
    'soft_skills.time': 'Gestión del Tiempo',
    'soft_skills.time_desc': 'Organización eficiente para cumplir con hitos y entregas críticas.',
    'exp.docente_role': 'Docente de Videojuegos',
    'exp.docente_company': 'Escuela de Arte de Granada',
    'exp.docente_period': '2023 - Presente',
    'exp.docente_desc': 'Impartición de módulos de Unity, C# y pipelines de arte 3D para ciclos formativos.',
    'exp.creative_role': 'Creative Specialist',
    'exp.creative_company': 'AndaluzIA',
    'exp.creative_period': '2022 - Presente',
    'exp.creative_desc': 'Desarrollo de contenido visual impulsado por IA y pipelines 3D para marketing digital.',
    'exp.freelance_role': 'Artista 3D Freelance',
    'exp.freelance_company': 'Varios Clientes',
    'exp.freelance_period': '2020 - 2022',
    'exp.freelance_desc': 'Creación de assets, entornos y visualizaciones arquitectónicas para diversos proyectos.',
    'lang.spanish': 'Español',
    'lang.english': 'Inglés',
    'lang.basque': 'Euskera',
    'lang.native': 'Nativo',
    'lang.pro': 'Profesional (C1)',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
