
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.models3d': '3D Models',
    'nav.contact': 'Contact',
    'nav.cv': 'CV',
    'nav.download_cv': 'Download CV',
    'hero.creative_specialist': 'Creative Specialist',
    'hero.title': 'JULEN VALLECILLOS',
    'hero.subtitle': '3D Artist • Level Designer • Unity Developer • Web Designer • E-Commerce • Video Game Trainer • Music Producer • Graphic Marketing Designer',
    'hero.view_projects': 'View Projects',
    'hero.download_cv': 'Download CV',
    'project.actual': 'Current Project',
    'project.in_development': 'In Development',
    'project.neon_run_desc': 'An atmospheric horror experience exploring the liminal spaces of the Backrooms. Developed in Unity with a focus on psychological tension and procedural environment generation.',
    'project.phase': 'Production Phase: Level Design & Atmospheric Lighting',
    'project.neon_run_name': '"Backrooms Origins"',
    'andaluzia.title': 'AndaluzIA',
    'andaluzia.subtitle': 'Digital Marketing & AI',
    'andaluzia.desc': 'At AndaluzIA, we merge traditional creativity with the infinite possibilities of AI. I develop high-impact visual marketing experiences using 3D pipelines and generative workflows.',
    'andaluzia.view_agency': 'View Agency',
    'darwin.title': 'Darwin & Co',
    'darwin.subtitle': 'Indie Game Studio',
    'darwin.desc': 'At Darwin & Co, we create unique interactive experiences. From experimental prototypes to polished indie titles, our focus is on innovative mechanics and immersive storytelling.',
    'darwin.view_studio': 'Visit Studio',
    'eag.title': 'Granada Art School',
    'eag.subtitle': 'Education',
    'eag.course': 'Introduction to Unity for 2D and 3D Games',
    'eag.desc': 'As a teacher, I guide my students through a 60-hour program. We divide the process into three critical phases to ensure a smooth and professional development.',
    'eag.download_plan': 'Download Plan (PDF)',
    'eag.feature1': 'Custom Mechanics',
    'eag.feature2': 'Particle Systems',
    'eag.feature3': 'C# Logic',
    'eag.feature4': 'Game AI',
    'social.title': 'Julengine',
    'social.desc': 'Explore my tutorials, workflows, and daily content on social media.',
    'social.youtube_desc': 'Devlogs, technical tutorials, and professional workflows.',
    'social.tiktok_desc': 'Quick 3D tips, Unity tricks, and daily insights.',
    'social.instagram_desc': 'My artistic side: Finished renders and visual gallery.',
    'skills.hard': 'Hard Skills',
    'skills.hard_desc': 'I master industry-standard software to bring any vision to the digital field.',
    'skills.soft': 'Soft Skills',
    'skills.soft_desc': 'Interpersonal qualities that enhance workflow and professional collaboration.',
    'experience.title': 'Experience',
    'experience.desc': 'My professional journey building worlds and training future talents.',
    'languages.title': 'Languages',
    'projects.title': 'Projects',
    'projects.subtitle': 'A deep look at my created worlds.',
    'projects.explore_all': 'Explore All',
    'projects.environment': 'Environment',
    'projects.view_details': 'View Details',
    'contact.cta_title': 'SHALL WE TALK?',
    'contact.cta_desc': 'I am available for creative projects, talks, or personalized tutoring. Let\'s build the interactive future together.',
    'contact.cta_button': 'Start',
    'contact.title': 'Let\'s Talk',
    'contact.subtitle': 'Do you have a project in mind or just want to say hi?',
    'contact.label_name': 'Name',
    'contact.placeholder_name': 'Your full name',
    'contact.label_email': 'Email',
    'contact.placeholder_email': 'email@example.com',
    'contact.label_message': 'Message',
    'contact.placeholder_message': 'Tell me about your project...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.success': 'Message sent successfully! (Simulated)',
    'contact.collabs': 'Collaborators & Friends',
    'contact.your_name': 'Your name',
    'contact.collab_cta': 'Collaborate',
    'projects_page.title': 'My Projects',
    'projects_page.view_more': 'View more',
    'projects.p1_title': 'Backrooms Origins (Videojuego)',
    'projects.p1_desc': 'An atmospheric horror experience exploring the liminal spaces of the Backrooms. Developed in Unity with a focus on psychological tension and procedural environment generation.',
    'projects.p2_title': 'Spectral Roulette (Videojuego)',
    'projects.p2_desc': 'A high-stakes supernatural gambling game where you bet your soul against spectral entities. Features unique card mechanics and a dark, noir aesthetic.',
    'projects.p3_title': 'Star Hunt (Videojuego)',
    'projects.p3_desc': 'An intergalactic exploration game where you track down dying stars to harvest their energy. Developed with a focus on stylized visuals and relaxing gameplay.',
    'projects.p4_title': 'BACKROOMS (Serie Anime)',
    'projects.p4_desc': 'An animated series project exploring the lore of the Backrooms through a unique anime lens. Focus on character-driven stories in an infinite, surreal world.',
    'projects.p5_title': 'Pokémon Mystery Battle Royale (Videogame)',
    'projects.p5_desc': 'A fan-made tactical battle royale experience featuring mystery dungeon mechanics and competitive multiplayer strategy.',
    'projects.p6_title': 'Coming Soon',
    'projects.p6_desc': 'New worlds and experiences are currently under development. Stay tuned for more updates on my creative journey.',
    'models_page.title': '3D Viewer',
    'models_page.subtitle': 'Interact directly with my models. You can rotate, zoom, and inspect the meshes.',
    'models_page.model_label': 'Model',
    'models_page.pbr_desc': 'Produced using Blender for modeling and Substance Painter for PBR (Physical Based Rendering) texturing.',
    'models_page.textures': '4K Textures',
    'models_page.game_ready': 'Game Ready',
    'models.m1_title': 'Modular Space Station',
    'models.m1_desc': 'Modular kitbash designed for optimization in real-time engines.',
    'models.m2_title': 'Underwater Creature',
    'models.m2_desc': 'Organic sculpture with manual retopology workflow.',
    'models.m3_title': 'Post-Apocalyptic Vehicle',
    'models.m3_desc': 'Focus on material wear and micro-details in textures.',
    'footer.rights': 'ALL RIGHTS RESERVED.',
    'skills.blender_desc': '3D modeling, sculpting, and photorealistic rendering for high-quality assets.',
    'skills.photoshop_desc': 'Digital retouching, texture design, and advanced visual post-production.',
    'skills.substance_desc': 'Professional PBR texturing following AAA industry standards.',
    'skills.unreal_desc': 'Creation of immersive worlds, dynamic lighting, and game logic.',
    'skills.unity_desc': 'Integral development of 2D and 3D games, from prototyping to publishing.',
    'skills.premiere_desc': 'Cinematic video editing, montage, and audiovisual narrative.',
    'skills.reaper_desc': 'Sound design and audio production optimized for interactive experiences.',
    'skills.capcut_desc': 'Advanced video editing for social media and short-form content.',
    'skills.claude_desc': 'Integration of advanced LLMs for creative and technical workflows.',
    'skills.gemini_desc': 'Leveraging Google\'s AI for research, coding, and content generation.',
    'skills.chatgpt_desc': 'Productivity optimization and automated logic using OpenAI\'s models.',
    'skills.vscode_desc': 'Professional environment for C#, web development, and scripting.',
    'skills.figma_desc': 'Collaborative UI/UX design and interactive prototyping.',
    'skills.freepik_desc': 'Management of high-quality graphic resources and visual assets.',
    'skills.photopea_desc': 'Advanced web-based image editing and PSD file management.',
    'skills.github_desc': 'Version control, collaborative development, and project hosting.',
    'soft_skills.verbal': 'Verbal Communication',
    'soft_skills.verbal_level': 'Expert',
    'soft_skills.written': 'Written Communication',
    'soft_skills.written_level': 'Expert',
    'soft_skills.team': 'Teamwork',
    'soft_skills.team_level': 'Expert',
    'soft_skills.problem': 'Problem Solving',
    'soft_skills.problem_level': 'Advanced',
    'soft_skills.org': 'Organisational Skills',
    'soft_skills.org_level': 'Expert',
    'soft_skills.time': 'Time Management',
    'soft_skills.time_level': 'Advanced',
    'soft_skills.critical': 'Critical Thinking',
    'soft_skills.critical_level': 'Expert',
    'soft_skills.creative': 'Creative Thinking',
    'soft_skills.creative_level': 'Expert',
    'soft_skills.lead': 'Leadership',
    'soft_skills.lead_level': 'Expert',
    'soft_skills.empathy': 'Empathy',
    'soft_skills.empathy_level': 'Expert',
    'soft_skills.piano': 'Piano',
    'soft_skills.piano_level': 'Advanced',
    'exp.docente_role': 'Game Development Teacher',
    'exp.docente_company': 'Granada Art School',
    'exp.docente_period': '2023 - Present',
    'exp.docente_desc': 'Teaching Unity, C#, and 3D art pipelines for vocational training cycles.',
    'exp.creative_role': 'Creative Specialist',
    'exp.creative_company': 'AndaluzIA',
    'exp.creative_period': '2022 - Present',
    'exp.creative_desc': 'Development of AI-driven visual content and 3D pipelines for digital marketing.',
    'exp.freelance_role': 'Freelance 3D Artist',
    'exp.freelance_company': 'Various Clients',
    'exp.freelance_period': '2020 - 2022',
    'exp.freelance_desc': 'Creation of assets, environments, and architectural visualizations for various projects.',
    'lang.spanish': 'Spanish',
    'lang.english': 'English',
    'lang.basque': 'Basque',
    'lang.french': 'French',
    'lang.catalan': 'Catalan',
    'lang.native': 'Native',
    'lang.pro': 'Professional (C1)',
    'lang.advanced': 'Advanced',
    'lang.basic': 'Basic',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.projects': 'Proyectos',
    'nav.models3d': 'Modelos 3D',
    'nav.contact': 'Contacto',
    'nav.cv': 'CV',
    'nav.download_cv': 'Descargar CV',
    'hero.creative_specialist': 'Creative Specialist',
    'hero.title': 'JULEN VALLECILLOS',
    'hero.subtitle': 'Artista 3D • Diseñador de Niveles • Desarrollador Unity • Diseñador Web • E-Commerce • Formador de Videojuegos • Productor Musical • Diseñador de Marketing Gráfico',
    'hero.view_projects': 'Ver Proyectos',
    'hero.download_cv': 'Descargar CV',
    'project.actual': 'Proyecto Actual',
    'project.in_development': 'En Desarrollo',
    'project.neon_run_desc': 'Una experiencia de terror atmosférico que explora los espacios liminales de las Backrooms. Desarrollado en Unity con un enfoque en la tensión psicológica y la generación procedural de entornos.',
    'project.phase': 'Fase de Producción: Diseño de Niveles e Iluminación Atmosférica',
    'project.neon_run_name': '"Backrooms Origins"',
    'andaluzia.title': 'AndaluzIA',
    'andaluzia.subtitle': 'Marketing Digital & IA',
    'andaluzia.desc': 'En AndaluzIA, fusionamos la creatividad tradicional con las posibilidades infinitas de la IA. Desarrollo experiencias de marketing visual de alto impacto utilizando pipelines 3D y flujos de trabajo generativos.',
    'andaluzia.view_agency': 'Ver Agencia',
    'darwin.title': 'Darwin & Co',
    'darwin.subtitle': 'Estudio de Videojuegos Indie',
    'darwin.desc': 'En Darwin & Co, creamos experiencias interactivas únicas. Desde prototipos experimentales hasta títulos indie pulidos, nuestro enfoque se centra en mecánicas innovadoras y narrativa inmersiva.',
    'darwin.view_studio': 'Visitar Estudio',
    'eag.title': 'Escuela de Arte de Granada',
    'eag.subtitle': 'Educación',
    'eag.course': 'Introducción a Unity para Videojuegos 2D y 3D',
    'eag.desc': 'Como docente, guío a mis alumnos a través de un programa de 60 horas. Dividimos el proceso en tres fases críticas para garantizar un desarrollo fluido y profesional.',
    'eag.download_plan': 'Descargar Plan (PDF)',
    'eag.feature1': 'Mecánicas Propias',
    'eag.feature2': 'Sistemas de Partículas',
    'eag.feature3': 'Lógica en C#',
    'eag.feature4': 'IA en Juegos',
    'social.title': 'Julengine',
    'social.desc': 'Explora mis tutoriales, procesos de trabajo y contenido diario en redes sociales.',
    'social.youtube_desc': 'Devlogs, tutoriales técnicos y pipelines de trabajo profesional.',
    'social.tiktok_desc': 'Tips rápidos de 3D, trucos de Unity y pinceladas del día a día.',
    'social.instagram_desc': 'Mi cara más artística: Renders terminados y galería visual.',
    'skills.hard': 'Hard Skills',
    'skills.hard_desc': 'Domino el software estándar de la industria para llevar cualquier visión al terreno digital.',
    'skills.soft': 'Soft Skills',
    'skills.soft_desc': 'Cualidades interpersonales que potencian el flujo de trabajo y la colaboración profesional.',
    'experience.title': 'Experiencia',
    'experience.desc': 'Mi trayectoria profesional construyendo mundos y formando a futuros talentos.',
    'languages.title': 'Idiomas',
    'projects.title': 'Proyectos',
    'projects.subtitle': 'Una mirada profunda a mis mundos creados.',
    'projects.explore_all': 'Explorar Todo',
    'projects.environment': 'Entorno',
    'projects.view_details': 'Ver Detalles',
    'contact.cta_title': '¿HABLAMOS?',
    'contact.cta_desc': 'Estoy disponible para proyectos creativos, charlas o tutorías personalizadas. Construyamos el futuro interactivo juntos.',
    'contact.cta_button': 'Comenzar',
    'contact.title': 'Hablemos',
    'contact.subtitle': '¿Tienes un proyecto en mente o solo quieres saludar?',
    'contact.label_name': 'Nombre',
    'contact.placeholder_name': 'Tu nombre completo',
    'contact.label_email': 'Email',
    'contact.placeholder_email': 'correo@ejemplo.com',
    'contact.label_message': 'Mensaje',
    'contact.placeholder_message': 'Cuéntame sobre tu proyecto...',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.success': '¡Mensaje enviado con éxito! (Simulado)',
    'contact.collabs': 'Colaboradores & Amigos',
    'contact.your_name': 'Tu nombre',
    'contact.collab_cta': 'Colabora',
    'projects_page.title': 'Mis Proyectos',
    'projects_page.view_more': 'Ver más',
    'projects.p1_title': 'Backrooms Origins (Videojuego)',
    'projects.p1_desc': 'Una experiencia de terror atmosférico que explora los espacios liminales de las Backrooms. Desarrollado en Unity con un enfoque en la tensión psicológica y la generación procedural de entornos.',
    'projects.p2_title': 'Spectral Roulette (Videojuego)',
    'projects.p2_desc': 'Un juego de apuestas sobrenaturales de alto riesgo donde apuestas tu alma contra entidades espectrales. Presenta mecánicas de cartas únicas y una estética noir oscura.',
    'projects.p3_title': 'Star Hunt (Videojuego)',
    'projects.p3_desc': 'Un juego de exploración intergaláctica donde rastreas estrellas moribundas para cosechar su energía. Desarrollado con un enfoque en visuales estilizados y jugabilidad relajante.',
    'projects.p4_title': 'BACKROOMS (Serie Anime)',
    'projects.p4_desc': 'Un proyecto de serie animada que explora el lore de las Backrooms a través de una lente de anime única. Enfoque en historias impulsadas por personajes en un mundo infinito y surrealista.',
    'projects.p5_title': 'Pokémon Mystery Battle Royale (Videogame)',
    'projects.p5_desc': 'Una experiencia fan-made de battle royale táctico que presenta mecánicas de mystery dungeon y estrategia multijugador competitiva.',
    'projects.p6_title': 'Próximamente',
    'projects.p6_desc': 'Nuevos mundos y experiencias están actualmente en desarrollo. Mantente al tanto para más actualizaciones sobre mi viaje creativo.',
    'models_page.title': 'Visualizador 3D',
    'models_page.subtitle': 'Interactúa directamente con mis modelos. Puedes rotar, hacer zoom e inspeccionar las mallas.',
    'models_page.model_label': 'Modelo',
    'models_page.pbr_desc': 'Producido utilizando Blender para el modelado y Substance Painter para el texturizado PBR (Physical Based Rendering).',
    'models_page.textures': '4K Texturas',
    'models_page.game_ready': 'Game Ready',
    'models.m1_title': 'Estación Espacial Modular',
    'models.m1_desc': 'Kitbash modular diseñado para optimización en motores de tiempo real.',
    'models.m2_title': 'Criatura Submarina',
    'models.m2_desc': 'Escultura orgánica con flujo de trabajo de retopología manual.',
    'models.m3_title': 'Vehículo Post-Apocalíptico',
    'models.m3_desc': 'Enfoque en desgaste de materiales y micro-detalles en las texturas.',
    'footer.rights': 'TODOS LOS DERECHOS RESERVADOS.',
    'skills.blender_desc': 'Modelado 3D, escultura y renderizado fotorrealista para assets de alta calidad.',
    'skills.photoshop_desc': 'Retoque digital, diseño de texturas y post-producción visual avanzada.',
    'skills.substance_desc': 'Texturizado PBR profesional siguiendo estándares de la industria AAA.',
    'skills.unreal_desc': 'Creación de mundos inmersivos, iluminación dinámica y lógica de juego.',
    'skills.unity_desc': 'Desarrollo integral de videojuegos 2D y 3D, desde prototipado hasta publicación.',
    'skills.premiere_desc': 'Edición de video cinematográfica, montaje y narrativa audiovisual.',
    'skills.reaper_desc': 'Diseño sonoro y producción de audio optimizado para experiencias interactivas.',
    'skills.capcut_desc': 'Edición de video avanzada para redes sociales y contenido de formato corto.',
    'skills.claude_desc': 'Integración de LLMs avanzados para flujos de trabajo creativos y técnicos.',
    'skills.gemini_desc': 'Aprovechamiento de la IA de Google para investigación, programación y generación de contenido.',
    'skills.chatgpt_desc': 'Optimización de productividad y lógica automatizada usando modelos de OpenAI.',
    'skills.vscode_desc': 'Entorno profesional para C#, desarrollo web y scripting.',
    'skills.figma_desc': 'Diseño de UI/UX colaborativo y prototipado interactivo.',
    'skills.freepik_desc': 'Gestión de recursos gráficos de alta calidad y activos visuales.',
    'skills.photopea_desc': 'Edición de imágenes avanzada basada en web y gestión de archivos PSD.',
    'skills.github_desc': 'Control de versiones, desarrollo colaborativo y alojamiento de proyectos.',
    'soft_skills.verbal': 'Comunicación Verbal',
    'soft_skills.verbal_level': 'Experto',
    'soft_skills.written': 'Comunicación Escrita',
    'soft_skills.written_level': 'Experto',
    'soft_skills.team': 'Trabajo en Equipo',
    'soft_skills.team_level': 'Experto',
    'soft_skills.problem': 'Resolución de Problemas',
    'soft_skills.problem_level': 'Avanzado',
    'soft_skills.org': 'Habilidades Organizativas',
    'soft_skills.org_level': 'Experto',
    'soft_skills.time': 'Gestión del Tiempo',
    'soft_skills.time_level': 'Avanzado',
    'soft_skills.critical': 'Pensamiento Crítico',
    'soft_skills.critical_level': 'Experto',
    'soft_skills.creative': 'Pensamiento Creativo',
    'soft_skills.creative_level': 'Experto',
    'soft_skills.lead': 'Liderazgo',
    'soft_skills.lead_level': 'Experto',
    'soft_skills.empathy': 'Empatía',
    'soft_skills.empathy_level': 'Experto',
    'soft_skills.piano': 'Piano',
    'soft_skills.piano_level': 'Avanzado',
    'exp.docente_role': 'Docente de Videojuegos',
    'exp.docente_company': 'Escuela de Arte de Granada',
    'exp.docente_period': '2023 - Presente',
    'exp.docente_desc': 'Impartición de módulos de Unity, C# y pipelines de arte 3D para ciclos formativos.',
    'exp.creative_role': 'Creative Specialist',
    'exp.creative_company': 'AndaluzIA',
    'exp.creative_period': '2022 - Presente',
    'exp.creative_desc': 'Desarrollo de contenido visual impulsado por IA y pipelines 3D para marketing digital.',
    'exp.freelance_role': 'Artista 3D Freelance',
    'exp.freelance_company': 'Varios Clientes',
    'exp.freelance_period': '2020 - 2022',
    'exp.freelance_desc': 'Creación de assets, entornos y visualizaciones arquitectónicas para diversos proyectos.',
    'lang.spanish': 'Español',
    'lang.english': 'Inglés',
    'lang.basque': 'Euskera',
    'lang.french': 'Francés',
    'lang.catalan': 'Catalán',
    'lang.native': 'Nativo',
    'lang.pro': 'Profesional (C1)',
    'lang.advanced': 'Avanzado',
    'lang.basic': 'Básico',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
